//PRINTING SOME NATURAL NUMBERS USING WHILE LOOP IN JS \
// let num = prompt('enter the number');
// num = Number.parseInt(num)
// let i = 1
// while(i <= num){
//     console.log(i); 
//     i++;
// }

// DO-WHILE LOOP IN JAVASCRIPT
// PRINTING SOME NATURAL NUMBERS USING WHILE LOOP IN JS..
// let i = 1;
// let num = prompt("enter the number");
// num = Number.parseInt(num);
// do{
//     console.log(i);
//     i++;
// }while(i<=num);
/*IF WE WANT TO EXECUTE OUR CODE ONLY FOR ONE TIME WE US E THE DO-WHILE LOOP IN JS AND OTHER PROGRAMMING LANGUAGES ALSO*/ 